Add example of searching user by name
microsoftgraph/msgraph-sdk-python pull request #358
Opened 2023-09-19 20:29 UTC by earthquakesan

Provide an end-to-end example of how to initialize users request with query parameters and search query. Reproduce the same behavior as in the Azure AD web console search.

2023-09-20 13:21 UTC, baywet requested changes
Thanks for the great contribution!
@samwelkanda for additional review

2023-09-20 13:21 UTC, baywet commented on docs/users_samples.md
> +async def get_user(user_name: str, client: GraphServiceClient) -> None:
could you rename the method to find user instead since this is not getting but rather finding the user?

2023-09-24 13:56 UTC, earthquakesan commented on docs/users_samples.md
> +async def get_user(user_name: str, client: GraphServiceClient) -> None:
@baywet done! lemme know if there is anything else I can improve in the snippet

2023-09-25 12:34 UTC, baywet approved these changes
Thanks for the contribution. @samwelkanda for final review and merge

2023-09-25 20:22 UTC, samwelkanda approved these changes

2023-09-25 20:48 UTC, merged