Added configuration example in README.md when configuring a GraphServiceClient behind a corporate HTTP proxy
microsoftgraph/msgraph-sdk-python pull request #525
Opened 2023-12-16 13:19 UTC by dabla

Added configuration example in README.md when configuring a GraphServiceClient behind a corporate HTTP proxy

2023-12-18 13:22 UTC, baywet requested changes
Thank you for the contribution.
Rather than duplicating information, what would you think about simply adding a Note on this readme, with a link that points to [this page](https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=python#configuring-the-http-proxy-for-the-client) ?

I understand the Azure Identity proxy configuration is not setup in that page, but you could PR the code snippet over there.

2023-12-18 13:55 UTC, dabla commented
> Thank you for the contribution. Rather than duplicating information, what would you think about simply adding a Note on this readme, with a link that points to [this page](https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=python#configuring-the-http-proxy-for-the-client) ?
> 
> I understand the Azure Identity proxy configuration is not setup in that page, but you could PR the code snippet over there.

I would like to adapt that [page](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/customize-client.md) but I can't find back the snippets in the repository.

2023-12-18 14:01 UTC, baywet commented
here it is
https://github.com/microsoftgraph/msgraph-snippets-python/blob/main/src/snippets/custom_clients.py

2023-12-18 14:03 UTC, dabla commented
> here it is https://github.com/microsoftgraph/msgraph-snippets-python/blob/main/src/snippets/custom_clients.py

Thank you Vincent! :)

2023-12-18 20:57 UTC, dabla commented
I cannot apply this example in the snippets as they are using another provider which doesn't support proxies in the constructor...

https://github.com/microsoftgraph/msgraph-snippets-python/pull/23

2023-12-18 21:15 UTC, baywet commented
Thanks for letting me know, I joined the conversation over there

2023-12-20 07:32 UTC, dabla commented
Hello Vincent, I think we can now merge this note refering the snippets also into the README.md now that Jason has merged the snippets?

2023-12-20 13:09 UTC, baywet requested changes

2023-12-20 13:09 UTC, baywet commented on README.md
> +opposed to the [httpx](https://www.python-httpx.org/) AsyncClient.  That's why we need to adapt the proxies dict before passing it to the [httpx](https://www.python-httpx.org/) AsyncClient.
```suggestion
> **Note**: Refer to the [following documentation page](https://learn.microsoft.com/graph/sdks/customize-client?tabs=python#configuring-the-http-proxy-for-the-client) if you need to configure an HTTP proxy.
```

2023-12-20 14:41 UTC, baywet approved these changes
Thanks for making the changes!

2023-12-20 14:42 UTC, baywet commented
@dabla would you mind replicating the changes [on the beta repo](https://github.com/microsoftgraph/msgraph-beta-sdk-python) please?

2023-12-20 15:02 UTC, merged

2023-12-20 15:03 UTC, dabla commented
> baywet

Just create a pull request for it: https://github.com/microsoftgraph/msgraph-beta-sdk-python/pull/299

2023-12-20 15:08 UTC, dabla commented
> Thanks for making the changes!

Thank you for guiding me through this process!

2023-12-20 15:08 UTC, baywet commented
no worries, thanks for the contributions!